package twitter

const APIBaseUrl = "https://api.twitter.com/1.1/"

var ResourceInfoMap = map[string]*ResourceInfo{
	"statuses/mentions_timeline": &ResourceInfo{
		EndPoint:       APIBaseUrl + "statuses/mentions_timeline.json",
		Authentication: true,
		HttpMethod:     "GET",
		RequiredArgs:   []string{},
		OptionalArgs: []string{"count", "since_id", "max_id",
			"contributor_details", "include_entities"},
	},
	"statuses/user_timeline": &ResourceInfo{
		EndPoint:       APIBaseUrl + "statuses/user_timeline.json",
		Authentication: true,
		HttpMethod:     "GET",
		RequiredArgs:   []string{},
		OptionalArgs: []string{"user_id", "screen_name", "since_id",
			"count", "trim_user", "exclude_replies", "contributor_details",
			"include_rts"},
	},
	"statuses/home_timeline": &ResourceInfo{
		EndPoint:       APIBaseUrl + "statuses/home_timeline.json",
		Authentication: true,
		HttpMethod:     "GET",
		RequiredArgs:   []string{},
		OptionalArgs: []string{"count", "since_id", "max_id", "trim_user",
			"exclude_replies", "contributor_details", "include_entities"},
	},
	"statuses/retweets_of_me": &ResourceInfo{
		EndPoint:       APIBaseUrl + "statuses/retweets_of_me.json",
		Authentication: true,
		HttpMethod:     "GET",
		RequiredArgs:   []string{},
		OptionalArgs: []string{"count", "since_id", "max_id", "trim_user",
			"include_entities", "include_user_entities"},
	},
	"statuses/show/:id": &ResourceInfo{
		EndPoint:       APIBaseUrl + "statuses/show/%v.json",
		Authentication: true,
		HttpMethod:     "GET",
		RequiredArgs:   []string{"id"},
		OptionalArgs: []string{"count", "trim_user", "include_my_retweet",
			"include_entities"},
	},
	"statuses/destroy/:id": &ResourceInfo{
		EndPoint:       APIBaseUrl + "statuses/destroy/%v.json",
		Authentication: true,
		HttpMethod:     "POST",
		RequiredArgs:   []string{"id"},
		OptionalArgs: []string{"count", "trim_user", "include_my_retweet",
			"include_entities"},
	},
	"statuses/update": &ResourceInfo{
		EndPoint:       APIBaseUrl + "statuses/update.json",
		Authentication: true,
		HttpMethod:     "POST",
		RequiredArgs:   []string{"status"},
		OptionalArgs: []string{"in_reply_to_status_id", "lat", "long",
			"place_id", "display_coordinates", "trim_user"},
	},
	"statuses/retweet/:id": &ResourceInfo{
		EndPoint:       APIBaseUrl + "statuses/retweet/%v.json",
		Authentication: true,
		HttpMethod:     "POST",
		RequiredArgs:   []string{"id"},
		OptionalArgs:   []string{"trim_user"},
	},
	"statuses/update_with_media": &ResourceInfo{
		EndPoint:       APIBaseUrl + "statuses/update_with_media.json",
		Authentication: true,
		HttpMethod:     "POST",
		RequiredArgs:   []string{"status", "media[]"},
		OptionalArgs: []string{"possibly_sensitive", "in_reply_to_status_id",
			"lat", "long", "place_id", "display_coordinates"},
	},
	"statuses/oembed": &ResourceInfo{
		EndPoint:       APIBaseUrl + "statuses/oembed.json",
		Authentication: true,
		HttpMethod:     "GET",
		RequiredArgs:   []string{"id", "url"},
		OptionalArgs: []string{"maxwidth", "hide_media", "hide_thread",
			"omit_script", "align", "related", "lang"},
	},
	"search/tweets": &ResourceInfo{
		EndPoint:       APIBaseUrl + "search/tweets.json",
		Authentication: true,
		HttpMethod:     "GET",
		RequiredArgs:   []string{"q"},
		OptionalArgs: []string{"geocode", "lang", "locate", "result_type",
			"count", "until", "since_id", "max_id", "include_entites",
			"callback"},
	},
}
